from app.models.estudiantes import Estudiante
from app.models.cursos import Curso
from app.models.notas import Nota
from app.models.asistencia import Asistencia
from app.models.comportamiento import Comportamiento
from app.models.materias import Materia
from app.models.usuarios import Usuario
from app.models.insumos import Insumo
from app.models.cursos_materias_docentes import CursoMateriaDocente
