"""init

Revision ID: 974f3bff1341
Revises: 
Create Date: 2025-12-10 02:59:11.929844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974f3bff1341'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('docente', 'administrativo', name='rol_usuario'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('cursos',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('anio_lectivo', sa.String(length=20), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('id_tutor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_docente'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_tutor'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curso')
    )
    op.create_table('cursos_materias_docentes',
    sa.Column('id_cmd', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_docente'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ),
    sa.PrimaryKeyConstraint('id_cmd'),
    sa.UniqueConstraint('id_curso', 'id_materia', name='uq_curso_materia')
    )
    op.create_table('estudiantes',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('matriculado', 'retirado', 'graduado', name='estado_estudiante'), nullable=True),
    sa.Column('id_curso_actual', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso_actual'], ['cursos.id_curso'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_estudiante'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('asistencia',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_cmd', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('presente', 'ausente', 'atraso', name='estado_asistencia'), nullable=False),
    sa.ForeignKeyConstraint(['id_cmd'], ['cursos_materias_docentes.id_cmd'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_table('comportamiento',
    sa.Column('id_comportamiento', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Enum('A', 'B', 'C', 'D', 'E', name='valor_comportamiento'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_comportamiento'),
    sa.UniqueConstraint('id_estudiante', 'id_curso', 'mes', name='uq_comportamiento')
    )
    op.create_table('insumos',
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_cmd', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('ponderacion', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cmd'], ['cursos_materias_docentes.id_cmd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_insumo'),
    sa.UniqueConstraint('id_cmd', 'nombre', name='uq_insumo_curso')
    )
    op.create_index(op.f('ix_insumos_id_insumo'), 'insumos', ['id_insumo'], unique=False)
    op.create_table('notas',
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id_insumo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_nota'),
    sa.UniqueConstraint('id_estudiante', 'id_insumo', name='uq_estudiante_insumo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_index(op.f('ix_insumos_id_insumo'), table_name='insumos')
    op.drop_table('insumos')
    op.drop_table('comportamiento')
    op.drop_table('asistencia')
    op.drop_table('estudiantes')
    op.drop_table('cursos_materias_docentes')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
