"""fix_insumo_constraint_allow_multiple_actividades

Revision ID: e731e43734b9
Revises: 9f2a4b1c6d78
Create Date: 2026-01-22 01:40:37.404007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e731e43734b9'
down_revision: Union[str, Sequence[str], None] = '9f2a4b1c6d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover la restricción de unicidad que impedía múltiples actividades del mismo tipo por trimestre
    op.drop_constraint('uq_proyecto_examen_por_trimestre', 'insumos', type_='unique')
    
    op.create_unique_constraint('uq_curso_nombre_anio', 'cursos', ['nombre', 'anio_lectivo'])
    op.alter_column('estudiantes', 'eliminado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('insumos', 'id_trimestre',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('insumos', 'tipo_insumo',
               existing_type=postgresql.ENUM('actividad', 'proyecto_trimestral', 'examen_trimestral', name='tipoinsumoenum'),
               nullable=False)
    op.alter_column('materias', 'eliminado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_trimestres_id_trimestre'), 'trimestres', ['id_trimestre'], unique=False)
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_trimestres_id_trimestre'), table_name='trimestres')
    op.alter_column('materias', 'eliminado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('insumos', 'tipo_insumo',
               existing_type=postgresql.ENUM('actividad', 'proyecto_trimestral', 'examen_trimestral', name='tipoinsumoenum'),
               nullable=True)
    op.alter_column('insumos', 'id_trimestre',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Restaurar la restricción en el downgrade
    op.create_unique_constraint('uq_proyecto_examen_por_trimestre', 'insumos', ['id_cmd', 'id_trimestre', 'tipo_insumo'])
    
    op.alter_column('estudiantes', 'eliminado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_curso_nombre_anio', 'cursos', type_='unique')
    # ### end Alembic commands ###
